
version: '3'

services:
  angular:
    build: ./docker/node
    ports:
      - "4200:4200"
    volumes:
      - ./content:/application
    tty: true  # docker run のオプションに対応

  # エンドユーザ向けのコンテンツ配布用
  server:
    build: ./docker/server
    ports:
      - "80:80"
    volumes:
      - ./content/app/dist:/usr/share/nginx/html/app

  api:
    build: ./docker/django
    volumes:
      - ./content:/application
    tty: true

  api-server:
    build: ./docker/api-server
    volumes:
      - ./content/api:/usr/share/nginx/html/api
    ports:
      - "3000:3000"